[project]
name = "pii-customer-support"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { email = "abbrooks@amplify.com" }
]
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "ipykernel>=7.4.0",
    "keyring>=25.7.0",
    "pandas>=3.0.6",
    "python-dotenv>=1.2.4",
    "requests>=2.34.2",
    "snowflake-connector-python>=4.8.0",
]

[project.scripts]
pii-customer-support = "pii_customer_support:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
