WITH sample_cases AS (
  SELECT CASE_ID, CASE_NUMBER, SUBJECT, CREATED_AT_UTC
  FROM PROD_TRANSFORMED.PREP_SALESFORCE.PREP_SALESFORCE__CASE_V2
  WHERE IS_FIVETRAN_ACTIVE = TRUE                -- current version of each case only
    AND CREATED_AT_UTC >= DATEADD(day, -7, CURRENT_TIMESTAMP())
)
SELECT 'email' AS source, c.CASE_NUMBER, e.CREATED_AT AS text_created_at,
       e.WAS_INCOMING AS is_from_customer, LEFT(e.TEXT_BODY, 300) AS text_preview
FROM sample_cases c
JOIN PROD_TRANSFORMED.PREP_SALESFORCE.PREP_SALESFORCE__EMAIL_MESSAGE e
  ON e.PARENT_ID = c.CASE_ID                     -- emails use PARENT_ID, not CASE_ID
UNION ALL
SELECT 'chat', c.CASE_NUMBER, m.CREATED_AT_UTC, NULL, LEFT(m.MESSAGING_SESSION_TRANSCRIPT, 300)
FROM sample_cases c
JOIN PROD_TRANSFORMED.PREP_SALESFORCE.PREP_SALESFORCE__MESSAGING_SESSION m
  ON m.CASE_ID = c.CASE_ID
UNION ALL
SELECT 'case_comment', c.CASE_NUMBER, k.CREATED_AT, NULL, LEFT(k.COMMENT_BODY, 300)
FROM sample_cases c
JOIN PROD_TRANSFORMED.PREP_SALESFORCE.PREP_SALESFORCE__CASE_COMMENT k
  ON k.CASE_ID = c.CASE_ID
ORDER BY CASE_NUMBER, text_created_at
LIMIT 50;